### ISSUE TITLE
API endpoints handle last_modified field

### ISSUE THREAD

**Issue by dbirman** [AllenNeuralDynamics/aind-data-access-api#105] opened 2024-11-26 17:46 UTC
**Is your feature request related to a problem? Please describe.**
We've changed the expected format of last_modified to try to be consistent, it is now: `datetime.now(tz=timezone.utc).isoformat().replace("+00:00", "Z")`

I think it would be preferable to enforce this through the API and not expect developers/users to remember to update the field when pushing updates. 

**Describe the solution you'd like**
All endpoints automatically update `last_modified` with the correct format.

**Comment by jtyoung84** [comment] 2024-12-02 17:22
Possible duplicate of https://github.com/AllenNeuralDynamics/aind-lambda-functions/issues/130

**Closed by jtyoung84** 2024-12-02 17:22 UTC
